#!/usr/bin/env python3

class graph:
	def __init__(self,gdict=None):
		if gdict is None:
			gdict = {}
		self.gdict = gdict

	def edges(self):
		return self.findedges()
	
	def getVertices(self):
		return list(self.gdict.keys())

# Find the distinct list of edges
	def findedges(self):
		edgename = []
		for vrtx in self.gdict:
				for nxtvrtx in self.gdict[vrtx]:
						if {nxtvrtx, vrtx} not in edgename:
								edgename.append({vrtx, nxtvrtx})
		return edgename
		
# Add the vertex as a key
	def addVertex(self, vrtx):
		if vrtx not in self.gdict:
				self.gdict[vrtx] = []

# Add the new edge
	def AddEdge(self, edge):
		edge = set(edge)
		(vrtx1, vrtx2) = tuple(edge)
		if vrtx1 in self.gdict:
				self.gdict[vrtx1].append(vrtx2)
		else:
				self.gdict[vrtx1] = [vrtx2]

def write_lp_format():
	return 0

def read_input():
	num_sedes, num_conexoes = input().split()
	num_sedes = int(num_sedes)
	num_conexoes = int(num_conexoes)

	sede_origem, sede_destino, demanda = input().split()
	sede_origem = int(sede_origem)
	sede_destino = int(sede_destino)
	demanda = int(demanda)

	custos = []
	for conexao in range(num_conexoes):
		aux = input().split()
		custos.append(int(aux[0]))
		custos.append(int(aux[1]))
		custos.append(float(aux[2]))

	return num_sedes, num_conexoes, sede_origem, sede_destino, demanda, custos

def criaGrafo(num_sedes, custos):
	graph_elements = {}
	g = graph(graph_elements)

	for i in range(num_sedes):
		g.addVertex(i)

	for i in range(0,len(custos),3):
		g.AddEdge({custos[i], custos[i+1]})

	return g

def criaDictCustos(conexoes,custos):
	custos_conexoes = {}

	j = 0
	for i in range(0,len(custos),3):
		custos_conexoes[tuple(conexoes[j])] = custos[i+2]
		j = j + 1
		
	print(custos_conexoes)
	return custos_conexoes

def main():
	num_sedes, num_conexoes, sede_origem, sede_destino, demanda, custos = read_input()
	# print(num_sedes, num_conexoes, sede_origem, sede_destino, demanda)
	print(custos)

	conexoes = criaGrafo(num_sedes, custos)
	
	custos_conexoes = criaDictCustos(conexoes.edges(), custos)

	return 0

if __name__ == "__main__":
	main()